[workspace]
changelog_config = "cliff.toml"
changelog_update = true
dependencies_update = false # dependabot will handle this
git_tag_enable = true
git_release_enable = false
pr_labels = ["release"]
allow_dirty = true
publish = false # no cargo publish, only git tag
publish_allow_dirty = false
semver_check = false
release_commits = "^🔖"
