name: CI

on:
  push:
    branches: [main]
    tags: ["*.*.*"]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  rust-build:
    name: Rust Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo install just --locked
      - run: just format-check
      - run: just lint
      - run: just build
      - run: just test
      - run: just coverage

      - name: upload test results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          fail_ci_if_error: true
          files: ./junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: upload coverage report
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo install just --locked
      - run: just docker-build
