name: Release

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu"]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            - grelinfo/grelsolar:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64