name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. 1.2.3)"
        required: true
      ref:
        description: "Git ref (branch, tag, or commit SHA)"
        required: true
        default: "main"
      dry_run:
        description: "Perform a dry run without pushing to Docker Hub"
        required: false
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event.inputs.dry_run != 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Generate release notes
        id: release_notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          target_commitish: ${{ github.event.inputs.ref }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t grelinfo/grelsolar:${{ github.event.inputs.tag }} .

      - name: Push Docker image
        if: github.event.inputs.dry_run != 'true'
        run: |
          docker push grelinfo/grelsolar:${{ github.event.inputs.tag }}
